language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install coveralls pycodestyle pep257 restructuredtext_lint testfixtures
  - python setup.py install
script:
  - python setup.py test
  - pycodestyle --ignore=E501,W503 mdmux tests *.py
  - pep257 mdmux tests
  - rst-lint README
  - coverage run --source=mdmux setup.py test
after_success:
  - coveralls
